# Generated by Django 5.0.1 on 2024-02-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(default='https://github.com/GuruRaj0305', max_length=400),
        ),
    ]
