# Generated by Django 5.0.1 on 2024-02-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0003_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
