# Generated by Django 5.0.1 on 2024-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0004_alter_myfile_file_alter_projects_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfile',
            old_name='file',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='description',
        ),
        migrations.AddField(
            model_name='myfile',
            name='about_yourself',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='github_id',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='insta_id',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='linkedin_id',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='whatspp_num',
            field=models.IntegerField(null=True),
        ),
    ]
