# Generated by Django 5.0.1 on 2024-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0005_rename_file_myfile_resume_remove_myfile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='whatspp_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
