# Generated by Django 5.0.1 on 2024-02-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0006_alter_myfile_whatspp_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='about_yourself',
        ),
    ]
