# Generated by Django 5.0.1 on 2024-02-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebpage', '0007_remove_myfile_about_yourself'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFile',
            new_name='MyDetail',
        ),
    ]
